export type Row = {
  firstName: string
  lastName: string
  age: number
  visits: number
  status: string
  progress: string
}

export const testData = [
  {
    firstName: 'Marcella Andres Trenious Jr.',
    lastName: 'Muller',
    age: 28,
    visits: 93,
    status: 'relationship',
    progress: '100',
  },
  {
    firstName: 'Dortha',
    lastName: 'Crist',
    age: 35,
    visits: 66,
    status: 'complicated',
    progress: '67',
  },
  {
    firstName: 'Eldon',
    lastName: 'Hane',
    age: 23,
    visits: 800,
    status: 'complicated',
    progress: '92',
  },
  {
    firstName: 'Justen',
    lastName: 'Larkin',
    age: 18,
    visits: 647,
    status: 'single',
    progress: '75',
  },
  {
    firstName: 'Nellie',
    lastName: 'Zieme',
    age: 34,
    visits: 958,
    status: 'relationship',
    progress: '60',
  },
  {
    firstName: 'Mikel',
    lastName: 'Grant',
    age: 31,
    visits: 860,
    status: 'relationship',
    progress: '71',
  },
  {
    firstName: 'Abigayle',
    lastName: 'Barrows',
    age: 22,
    visits: 89,
    status: 'relationship',
    progress: '53',
  },
  {
    firstName: 'Favian',
    lastName: 'Hagenes',
    age: 26,
    visits: 783,
    status: 'complicated',
    progress: '39',
  },
  {
    firstName: 'Sigrid',
    lastName: 'Windler',
    age: 22,
    visits: 863,
    status: 'relationship',
    progress: '43',
  },
  {
    firstName: 'Zackary',
    lastName: 'Casper',
    age: 2,
    visits: 88,
    status: 'relationship',
    progress: '34',
  },
  {
    firstName: 'Kathlyn',
    lastName: 'Koss',
    age: 29,
    visits: 1000,
    status: 'single',
    progress: '100',
  },
  {
    firstName: 'Laurie',
    lastName: 'Kerluke',
    age: 21,
    visits: 190,
    status: 'single',
    progress: '10',
  },
  {
    firstName: 'Sigrid',
    lastName: 'Windler',
    age: 22,
    visits: 863,
    status: 'relationship',
    progress: '43',
  },
  {
    firstName: 'Zackary',
    lastName: 'Casper',
    age: 2,
    visits: 88,
    status: 'relationship',
    progress: '34',
  },
  {
    firstName: 'Kathlyn',
    lastName: 'Koss',
    age: 29,
    visits: 1000,
    status: 'single',
    progress: '100',
  },
  {
    firstName: 'Laurie',
    lastName: 'Kerluke',
    age: 21,
    visits: 190,
    status: 'single',
    progress: '10',
  },
  {
    firstName: 'Sigrid',
    lastName: 'Windler',
    age: 22,
    visits: 863,
    status: 'relationship',
    progress: '43',
  },
  {
    firstName: 'Zackary',
    lastName: 'Casper',
    age: 2,
    visits: 88,
    status: 'relationship',
    progress: '34',
  },
  {
    firstName: 'Kathlyn',
    lastName: 'Koss',
    age: 29,
    visits: 1000,
    status: 'single',
    progress: '100',
  },
  {
    firstName: 'Laurie',
    lastName: 'Kerluke',
    age: 21,
    visits: 190,
    status: 'single',
    progress: '10',
  },
]
